services:
  - type: web
    name: medpass
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medpass-db
          property: connectionString

databases:
  - name: medpass-db
    plan: free
